### ISSUE TITLE
Changing settings require restart

### ISSUE THREAD

**Issue by idleberg** [leifmariposa/atom-build-ccs#1]
I came across this before, but I was hoping you could think of a solution. Updating the settings won't have an effect until you restart Atom. Seems the methods of a build provider are only run once when Atom is launched. I also tried using `preBuild()`, but that didn't do anything. Any ideas?

**Comment by leifmariposa** [comment]
I found the solution in https://github.com/AtomBuild/atom-build-make.
Fixed in v0.1.3
